image: nicolaspetton/emacs

.test_job_template: &test_job_definition
  script:
    - evm use $EMACS_VERSION
    - emacs --version
    - make ci-dependencies
    - make check

test:emacs:25.1:
  variables:
    EMACS_VERSION: "emacs-25.1-travis"
  <<: *test_job_definition

test:emacs:25.3:
  variables:
    EMACS_VERSION: "emacs-25.3-travis"
  <<: *test_job_definition

test:emacs:26:
  variables:
    EMACS_VERSION: "emacs-26-pretest-travis"
  <<: *test_job_definition
