.test_job_template: &test_job_definition
  script:
    - emacs --version
    - make ci-dependencies
    - make check

test:emacs:25.1:
  image: registry.gitlab.com/damiencassou/emacs-ci-docker:25.1
  <<: *test_job_definition

test:emacs:25.3:
  image: registry.gitlab.com/damiencassou/emacs-ci-docker:25.3
  <<: *test_job_definition

test:emacs:26:
  image: registry.gitlab.com/damiencassou/emacs-ci-docker:26.0.91
  <<: *test_job_definition
